-- MySQL Script generated by MySQL Workbench
-- Mon Sep 21 20:21:19 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Mercado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mercado` (
  `over/under` INT NOT NULL,
  `cuota over` DOUBLE NOT NULL,
  `cuota under` DOUBLE NOT NULL,
  `dinero over` DOUBLE NOT NULL,
  `dinero under` DOUBLE NOT NULL,
  `Fecha` DATETIME NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`over/under`, `Fecha`, `Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `Local` VARCHAR(30) NOT NULL,
  `Visitante` VARCHAR(30) NOT NULL,
  `Fecha` DATETIME NOT NULL,
  PRIMARY KEY (`Local`, `Visitante`),
  INDEX `fecha_idx` (`Fecha` ASC) VISIBLE,
  CONSTRAINT `fecha`
    FOREIGN KEY (`Fecha`)
    REFERENCES `mydb`.`Mercado` (`Fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `Email` VARCHAR(45) NOT NULL,
  `Nombre` VARCHAR(30) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `Edad` INT NOT NULL,
  `num_tarjeta` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`Email`, `num_tarjeta`),
  CONSTRAINT `email`
    FOREIGN KEY (`Email`)
    REFERENCES `mydb`.`Mercado` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Banco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Banco` (
  `num_tarjeta` VARCHAR(45) NOT NULL,
  `Saldo` DOUBLE NOT NULL,
  `Nom_banco` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`num_tarjeta`),
  CONSTRAINT `num_tarjeta`
    FOREIGN KEY (`num_tarjeta`)
    REFERENCES `mydb`.`Usuario` (`num_tarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
