// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webAPI.Models;

namespace webAPI.Migrations
{
    [DbContext(typeof(PlaceMyBetContext))]
    [Migration("20201112201246_m2")]
    partial class m2
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webAPI.Models.Apuesta", b =>
                {
                    b.Property<int>("ApuestaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Cuota")
                        .HasColumnType("double");

                    b.Property<double>("Dinero")
                        .HasColumnType("double");

                    b.Property<string>("Fecha")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Id_Mercado")
                        .HasColumnType("int");

                    b.Property<string>("Id_Usuario")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("MercadoId")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_Cuota")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<double>("Tipo_Mercado")
                        .HasColumnType("double");

                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("ApuestaId");

                    b.HasIndex("MercadoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Apuestas");

                    b.HasData(
                        new
                        {
                            ApuestaId = 1,
                            Cuota = 1.8700000000000001,
                            Dinero = 200.0,
                            Fecha = "2020-10-14",
                            Id_Mercado = 1,
                            Id_Usuario = "AnaRS@gmail.com",
                            Tipo_Cuota = "over",
                            Tipo_Mercado = 1.5
                        },
                        new
                        {
                            ApuestaId = 2,
                            Cuota = 2.3900000000000001,
                            Dinero = 150.0,
                            Fecha = "2020-09-15",
                            Id_Mercado = 2,
                            Id_Usuario = "JuanPL@gmail.com",
                            Tipo_Cuota = "under",
                            Tipo_Mercado = 2.5
                        },
                        new
                        {
                            ApuestaId = 3,
                            Cuota = 1.9199999999999999,
                            Dinero = 175.0,
                            Fecha = "2020-09-16",
                            Id_Mercado = 3,
                            Id_Usuario = "PepeGB@gmail.com",
                            Tipo_Cuota = "over",
                            Tipo_Mercado = 3.5
                        });
                });

            modelBuilder.Entity("webAPI.Models.Evento", b =>
                {
                    b.Property<int>("EventoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Fecha")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Local")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Visitante")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("EventoId");

                    b.ToTable("Eventos");

                    b.HasData(
                        new
                        {
                            EventoId = 1,
                            Fecha = "2020-10-17",
                            Local = "Valencia",
                            Visitante = "Espanyol"
                        },
                        new
                        {
                            EventoId = 2,
                            Fecha = "2020-10-30",
                            Local = "Barcelona",
                            Visitante = "Valladolid"
                        },
                        new
                        {
                            EventoId = 3,
                            Fecha = "2020 -10-23",
                            Local = "Madrid",
                            Visitante = "Villareal"
                        });
                });

            modelBuilder.Entity("webAPI.Models.Mercado", b =>
                {
                    b.Property<int>("MercadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Cuota_Over")
                        .HasColumnType("double");

                    b.Property<double>("Cuota_Under")
                        .HasColumnType("double");

                    b.Property<double>("Dinero_Over")
                        .HasColumnType("double");

                    b.Property<double>("Dinero_Under")
                        .HasColumnType("double");

                    b.Property<int?>("EventoId")
                        .HasColumnType("int");

                    b.Property<int>("Id_Evento")
                        .HasColumnType("int");

                    b.Property<double>("Tipo_Mercado")
                        .HasColumnType("double");

                    b.HasKey("MercadoId");

                    b.HasIndex("EventoId");

                    b.ToTable("Mercados");

                    b.HasData(
                        new
                        {
                            MercadoId = 1,
                            Cuota_Over = 1.4299999999999999,
                            Cuota_Under = 2.8500000000000001,
                            Dinero_Over = 100.0,
                            Dinero_Under = 50.0,
                            Id_Evento = 1,
                            Tipo_Mercado = 1.5
                        },
                        new
                        {
                            MercadoId = 2,
                            Cuota_Over = 1.8999999999999999,
                            Cuota_Under = 1.8999999999999999,
                            Dinero_Over = 100.0,
                            Dinero_Under = 100.0,
                            Id_Evento = 2,
                            Tipo_Mercado = 2.5
                        },
                        new
                        {
                            MercadoId = 3,
                            Cuota_Over = 2.8500000000000001,
                            Cuota_Under = 1.4299999999999999,
                            Dinero_Over = 50.0,
                            Dinero_Under = 100.0,
                            Id_Evento = 3,
                            Tipo_Mercado = 3.5
                        });
                });

            modelBuilder.Entity("webAPI.Models.Usuario", b =>
                {
                    b.Property<string>("UsuarioId")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<string>("Apellido")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            UsuarioId = "AnaRS@gmail.com",
                            Apellido = "Rodríguez Sánchez",
                            Edad = 25,
                            Nombre = "Ana"
                        },
                        new
                        {
                            UsuarioId = "JuanPL@gmail.com",
                            Apellido = "Pérez López",
                            Edad = 27,
                            Nombre = "Juan"
                        },
                        new
                        {
                            UsuarioId = "PepeGB@gmail.com",
                            Apellido = "Gómez Botella",
                            Edad = 23,
                            Nombre = "Pepe"
                        });
                });

            modelBuilder.Entity("webAPI.Models.Apuesta", b =>
                {
                    b.HasOne("webAPI.Models.Mercado", "Mercado")
                        .WithMany("ListaApuestas")
                        .HasForeignKey("MercadoId");

                    b.HasOne("webAPI.Models.Usuario", "Usuario")
                        .WithMany("Apuestas")
                        .HasForeignKey("UsuarioId");
                });

            modelBuilder.Entity("webAPI.Models.Mercado", b =>
                {
                    b.HasOne("webAPI.Models.Evento", "Evento")
                        .WithMany("ListaMercados")
                        .HasForeignKey("EventoId");
                });
#pragma warning restore 612, 618
        }
    }
}
